apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serviceA.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.serviceA.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.serviceA.name }}
    spec:
      containers:
      - name: {{ .Values.serviceA.name }}
        image: {{ .Values.serviceA.image }}
        ports:
        - containerPort: {{ .Values.serviceA.port }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serviceB.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.serviceB.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.serviceB.name }}
    spec:
      containers:
      - name: {{ .Values.serviceB.name }}
        image: {{ .Values.serviceB.image }}
        ports:
        - containerPort: {{ .Values.serviceB.port }}
