apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceA.name }}
spec:
  ports:
    - port: 8080
  selector:
    app: {{ .Values.serviceA.name }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceB.name }}
spec:
  ports:
    - port: 8080
  selector:
    app: {{ .Values.serviceB.name }}
