name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Minikube
        uses: manusa/actions-setup-minikube@v2
        with:
          minikube-version: 'latest'
          kubernetes-version: 'v1.21.0' # Specify the Kubernetes version you need
          driver: 'docker'

      - name: Start Minikube
        run: minikube start

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Deploy Helm Chart
        run: helm upgrade --install test-services ./test-services

      - name: Apply Envoy Filter
        run: kubectl apply -f envoyfilter.yml