name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup_services:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Set up Minikube
    - name: Set up Minikube
      run: |
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube /usr/local/bin/
        minikube start --driver=none

    # Install Istio
    - name: Install Istio
      run: |
        curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.11.4 sh -
        cd istio-1.11.4
        export PATH=$PWD/bin:$PATH
        istioctl install --set profile=demo -y
        kubectl label namespace default istio-injection=enabled

    # Set up Helm
    - name: Install Helm
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh

    # Deploy services using Helm
    - name: Deploy Services
      run: |
        helm upgrade --install my-test-services ./test-services

    # Apply EnvoyFilter
    - name: Apply EnvoyFilter
      run: |
        kubectl apply -f envoyfilter.yaml

  run_tests:
    runs-on: ubuntu-latest
    needs: setup_services

    steps:
    - uses: actions/checkout@v2

    - name: Install JMeter
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jre
        wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.4.1.tgz
        tar -xvzf apache-jmeter-5.4.1.tgz
        export JMETER_HOME=$(pwd)/apache-jmeter-5.4.1
        export PATH=$PATH:$JMETER_HOME/bin

    - name: Run JMeter Tests
      run: |
        jmeter -n -t test_plan.jmx -l results.jtl

    - name: Check Test Results
      run: |
        cat results.jtl
