name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Minikube
        uses: manusa/actions-setup-minikube@v2.11.0
        with:
          minikube version: 'v1.33.0'
          kubernetes version: 'v1.30.0'
          driver: 'docker'

      - name: Start Minikube
        run: minikube start

      - name: Install Istio
        run: |
          curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.18.0 sh -
          cd istio-1.18.0
          export PATH=$PWD/bin:$PATH
          istioctl install --set profile=demo -y

      - name: Verify Istio Installation
        run: kubectl get pods -n istio-system

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Deploy Helm Chart
        run: helm upgrade --install test-services ./test-services

      # Apply EnvoyFilter
      - name: Apply EnvoyFilter
        run: |
          kubectl apply -f envoyfilter.yaml

  run_tests:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - uses: actions/checkout@v2

      - name: Install JMeter
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jre
          wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xvzf apache-jmeter-5.6.3.tgz
          export JMETER_HOME=$(pwd)/apache-jmeter-5.6.3
          export PATH=$PATH:$JMETER_HOME/bin

      - name: Run JMeter Tests
        run: |
          jmeter -n -t test_plan.jmx -l results.jtl

      - name: Check Test Results
        run: |
          cat results.jtl

  test_envoy_filter:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Requests Library
        run: |
          python -m pip install requests

      - name: Run Envoy Filter Test
        run: |
          python test_envoy_filter.py